import type { Metadata } from 'next';
import LegalPage, { type LegalBlock } from '@/components/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    "Flyrlink's Privacy Policy describing how we collect, process, use, store, and disclose Personal Data of Users in accordance with the DPDP Act, 2023.",
};

const blocks: LegalBlock[] = [
  {
    type: 'p',
    text: 'This Privacy Policy describes how the Company collects, processes, uses, stores and discloses Personal Data of Users of its Website and related services. For the purposes of the Digital Personal Data Protection Act, 2023 ("DPDP Act"), the Company acts as a Data Fiduciary in respect of Personal Data processed through the Website. The Company and its affiliates including its holding companies, parents, subsidiaries and allied partners, recognize the importance of protecting the privacy of Users and their personal data. The Company is committed to safeguarding the privacy of Users and their personal data in accordance with applicable data protection laws, regulations and industry standards.',
  },
  {
    type: 'p',
    text: 'The collection, processing, disclosure and usage of information by the Company is governed by this Policy, which details the nature of information collected, contents of information collected, details of processing, protecting, storing and archiving of information by the Company and the reasoning explaining the foregoing. The Company is involved in the business of operating technology platforms, applications and web-interfaces for persons or Users to access details of our products, services and software. By accessing or using the website or application, you are explicitly consenting to the contents of this Policy. You must read the contents of this Policy before accessing the website or applications.',
  },
  {
    type: 'p',
    text: 'Your Consent: By visiting the Website or setting up or creating a User Account on the Website for availing the Services on the Website at such time, the User signifies its acceptance to the provisions of the Privacy Policy.',
  },
  {
    type: 'p',
    text: 'This Privacy Policy (i) is an electronic record under the Information Technology Act, 2000 read with rules and regulations made thereunder and is generated by a computer system; and (ii) will not require any physical, electronic, or digital signature. In case of any non-compliance of the Privacy Policy by the User, we shall have the right to terminate your access to the Services or any part thereof, or your usage rights to the Website immediately, or remove non-compliant information, or both, as the case may be.',
  },

  { type: 'h2', text: 'Collection of Information' },
  {
    type: 'p',
    text: 'The Company may collect information which may include Personal Data and Ancillary Data from the User upon registration on the Website or when the User avails the Services. You can browse certain sections of the Website without being a registered member; however, to avail certain Services on the Website, the User is required to register with the Website. For avoidance of doubt, the terms Personal Data and Personal Information are used synonymously.',
  },
  {
    type: 'p',
    text: 'In accordance with the Digital Personal Data Protection Act, 2023 (DPDP Act), "Personal Data" refers to any data about an individual who is identifiable by or in relation to such data. To provide and improve our services, we collect Personal Data as well as Ancillary Data (information related to how you access and use our platforms). The information we collect falls into the following categories:',
  },

  { type: 'h3', text: 'A. Information You Provide to Us' },
  {
    type: 'ul',
    items: [
      'Account & Registration Data: Information provided during User Account creation, including your name, address, country of residence, email address, phone number, unique identifiers, and account preferences (such as favorites and history).',
      'Communication Data: Information you share with us through emails, electronic messages, telephonic conversations, or virtual or online meetings.',
    ],
  },

  { type: 'h3', text: 'B. Automatically Collected Information (Ancillary Data)' },
  {
    type: 'p',
    text: 'When you interact with our Products, software, solutions, or content, we automatically gather data regarding your usage patterns to ensure seamless Service provision. This includes:',
  },
  {
    type: 'ul',
    items: [
      'Device & Network Data: Your IP address, domain name, and other related network identifiers.',
      'Usage & Interaction Data: Timestamps, search queries, text prompts, User feedback, overall User behaviour, and interaction patterns with our services.',
    ],
  },

  { type: 'h3', text: 'C. Information from Other Sources' },
  {
    type: 'p',
    text: 'Information legitimately obtained from third parties, partners, or other sources as permitted by Applicable Laws.',
  },
  {
    type: 'p',
    text: 'By providing Personal Information and Ancillary Information to the Company, you explicitly consent to the collection, usage and disclosure of the foregoing information, as permitted by Applicable Laws. By using our products and services, you authorize us to gather, parse, and retain basic data related to the provision of the services and products.',
  },

  { type: 'h2', text: 'Voluntary Disclosure & Data Authenticity' },
  {
    type: 'p',
    text: 'All information you share with us is deemed to be disclosed willingly and without any coercion. You are solely responsible for the authenticity and accuracy of the information you provide. The Company does not verify this data and assumes no liability for any misrepresentation, fraud, or negligence regarding the information provided to us.',
  },

  { type: 'h2', text: 'Usage of Collected Information' },
  {
    type: 'p',
    text: 'The Company may collect your Personal Data and Ancillary Information for the following purposes:',
  },
  {
    type: 'ul',
    items: [
      'Improve User experience and communicate with you with regards to its Products, Services, software and promotional offers.',
      'Address complaints, resolve disputes, and diagnose technical issues.',
      'Maintain a secure environment on the Website and safeguard the integrity of the Website, the Services, and their Users.',
      'Process payments and recover amounts due in connection with the Services.',
      'Personalise and enhance User experience on the Website, including sending relevant promotional or marketing communications.',
      'Identify, prevent, and protect against errors, fraud, and any unlawful or prohibited activities.',
      'Administer, enforce, and notify Users of applicable terms and conditions.',
      'Process and fulfil User requests for Services and respond to feedback, comments, or queries.',
      'Communicate with the User for service-related or administrative purposes.',
      'Enable our business partners or associates to deliver tailored communications or content to you, where permitted.',
      'Notify Users of important announcements, modifications to the Services, or changes to the Website, policies, or terms.',
      'Carry out any other purpose disclosed to you at the time of collection, subject to obtaining your consent where required.',
    ],
  },
  {
    type: 'p',
    text: 'Additionally, the Company may use the information collected for observing, improving and administering the quality of Services and Products, for sending information and push notifications towards new updates and changes, for conducting market research, troubleshooting, error protection and other additional objectives which may be implemented by the Company to comply with Applicable Laws and to establish an effective channel of communication.',
  },

  { type: 'h2', text: 'Disclosure of Collected Information' },
  {
    type: 'p',
    text: 'The Company will not publish your information provided by you. We will treat your information as confidential and will not sell or lease your information to third parties, save and except for:',
  },
  {
    type: 'ul',
    items: [
      'Under the mandate of Applicable Laws, judicial order, or instructions received from regulatory, statutory or local bodies.',
      'In the event of merger, acquisition, bankruptcy or takeover of the Company.',
      'Disclosure within group companies and affiliates with the covenant that information so shared will be maintained with strict confidentiality.',
    ],
  },
  {
    type: 'p',
    text: 'The Company may disclose your information to provide services, enforce or apply applicable Terms and Conditions or terms of use, to protect its rights, titles, interests or safety of the Company, its assets and its representatives. This includes providing information to one or more lending partners, and exchanging information with other companies or agencies that work for fraud prevention.',
  },
  {
    type: 'p',
    text: 'You provide explicit consent to the Company for sharing your Personal Information with third parties that provide services on its behalf or with whom the Company has partnered to offer a specific product or service. These third parties are required to maintain necessary confidentiality and secrecy arrangements with the Company. We shall not assume responsibility for the transfer of any personal identification information due to data loss or distribution, media storage delineation or corruption, power outages, natural disasters, civil unrest, acts of vandalism, sabotage, terrorism, or any other unforeseen event beyond our control. Additionally, our Privacy Policy does not extend to the utilization of cookies by our partners and affiliates, as we lack access to or authority over such cookies.',
  },

  { type: 'h2', text: 'Amendment or Update to Personal Information' },
  {
    type: 'p',
    text: 'In the event that your Personal Information is subject to amendment or update at your end, you may connect with us for corrections, deletion of errors or updating information at support@flyrlink.com. For verification of changes, we request you to provide supportive documentation or information as may be deemed necessary by the Company to verify changes requested.',
  },

  { type: 'h2', text: 'Security of Information' },
  {
    type: 'p',
    text: 'At the Company, paramount importance is attributed to the security of Personal and Ancillary Information. To ensure the security of your information, suitable physical, electronic and managerial procedures are in place to safeguard and secure the information collected. When gathering data, we securely gather your personal information on a protected server, employing firewalls for added security. While we cannot ensure absolute security, these measures significantly impede hackers from decrypting your details. We uphold physical, electronic, and procedural safeguards throughout the collection, storage, and disclosure of your information. The Company may use third-party vendors, service providers and suppliers to perform various functions on its behalf, such as managing customer information, analysing data, and maintaining its websites and databases (if any). These service providers are not authorized to use Personal Information for any other purpose or to contact you outside of their contracted services. If you believe your account or information is compromised, please notify the Company immediately at support@flyrlink.com.',
  },
  {
    type: 'p',
    text: 'The information and data collected from you may be transferred to, stored, and processed in any location permitted by Applicable Laws. By submitting information to us, you consent to this transfer, storage, and processing. We will take reasonable steps to ensure that your information is treated securely and in accordance with this Policy. When accessing the website and its contents, you acknowledge the inherent security risks of transmitting data over the internet. Therefore, your use of the website and application is at your own risk, and we bear no responsibility for any information disclosure resulting from transmission errors, unauthorized access by third parties, or other acts beyond our control. You agree not to hold us liable for any security breaches. Should we become aware of any security breach involving your information, we will promptly notify you and take appropriate action to the best of our ability to address the breach.',
  },

  { type: 'h2', text: 'Connecting your User Account to Email Account' },
  {
    type: 'p',
    text: 'The User may choose to integrate one or more of your email accounts with your User Account on the Website for enhanced functionality. Such integration will occur only upon your explicit consent, including authentication via a confirmation email sent to your registered email address. The User will be specifically prompted each time to confirm whether you wish to link your email account(s) with your User Account on the Website. Integration will not take place unless you provide express authorization.',
  },
  {
    type: 'p',
    text: 'You are advised to carefully review the permissions requested prior to granting consent for integration. You retain full control over such integration and may, at any time, revoke access or de-link your connected email account(s) through the account settings available on the Website. Upon such de-linking, the Company will cease further access to the integrated email account(s), subject to retention requirements under Applicable Laws.',
  },
  {
    type: 'p',
    text: 'Additionally, where required for account functionality, profile display, or service features, the Company may upload and display your profile image on the Website. By voluntarily providing such image, you consent to its use for the intended Website functionality. You may modify or remove your profile image at any time through your account settings.',
  },

  { type: 'h2', text: 'Phishing and Online Fraud' },
  {
    type: 'p',
    text: 'There exist in the market third-party websites which imitate legitimate websites to obtain and steal personal and financial information. Such illegitimate practices are of great concern to the Company and in the event you come across any such material or interaction from a third party, please report it to support@flyrlink.com. The Company is committed to taking all measures necessary to secure the Website and other services. In rare cases, certain Users may request you to communicate outside the Website, including depositing money. You should refrain from interacting with such Users and should never deposit or send money outside the Website.',
  },

  { type: 'h2', text: 'Account Deletion' },
  {
    type: 'p',
    text: "The User may choose to delete the User Account on the Website and any information associated with it at any point of time. Such a request for deletion must be sent in writing to support@flyrlink.com. In the event the User makes a request for deletion of the User Account or data therein, the User will no longer be able to access the Website or use the Services, and we reserve the right to not provide the User any Services through the Website. In the event of your request, we may delete the User's information or de-identify it so that it is anonymous and no longer attributable to you. Notwithstanding anything contained herein, we may retain some or all of the User's information in accordance with our policies or requirements under Applicable Laws.",
  },

  { type: 'h2', text: 'Public Profile' },
  {
    type: 'p',
    text: 'The profile created by the User on the Website is and will be publicly accessible unless otherwise indicated. Public profiles are indexed by search engines such as Google, which may include displaying your profile and information therein as part of the search results. To prevent Google indexing, you may opt not to have your profile included in the Google indexing.',
  },

  { type: 'h2', text: 'Exclusions to the Policy' },
  {
    type: 'p',
    text: 'This Policy does not apply to information other than Personal and Ancillary Information collected by us during your access of our Website, products, services and software. This Policy does not apply in case of any information shared by you which is not solicited by the Company. Our Website, products and software may contain links to third-party websites and such websites are not under our control. In case you are directed to any of said websites, you are suggested to exercise discretion and your access and usage of the third-party websites shall be entirely at your own risk and we disclaim any liability for any issues arising out of your redirection, access and usage of third-party websites and contents thereof.',
  },

  { type: 'h2', text: 'Retention of Information' },
  {
    type: 'p',
    text: 'The Company will retain Personal and Ancillary Information as long as it is necessary to fulfil the purposes outlined in this policy, and as permitted by Applicable Laws. Once the business need is fulfilled or the purpose is no longer valid, the Company will either delete or anonymize the Personal Information. In cases where it is not possible, the Company will isolate the information from any further processing.',
  },

  { type: 'h2', text: 'Update to the Policy' },
  {
    type: 'p',
    text: 'This Privacy Policy and contents therein may change from time to time and all updates regarding the same shall be posted on our website. The Company reserves the right to change this Privacy Policy and related documentation as and when it deems fit.',
  },

  { type: 'h2', text: 'Addressing your Concerns' },
  {
    type: 'p',
    text: 'In the event of a security breach of Company systems, the Company will notify you through your authorized email address within 72 hours of the discovery of the breach. You may request details of personal information which we hold about you from the undersigned. There is no fee payable for this. If you would like a copy of the information held on you, please write to us at support@flyrlink.com.',
  },
  {
    type: 'p',
    text: 'In accordance with the Information Technology Act, 2000 and the rules made thereunder, the name and contact details of the Grievance Officer are provided below.',
  },
  {
    type: 'ul',
    items: [
      'Name: Raj Bharath',
      'Email Address: raj.bharath@flyrlink.com',
      'Physical Address: Unit 407, 4th floor Jain Sadguru Image Capital Park, Image Garden Road, Hyderabad - 500081.',
    ],
  },

  { type: 'h2', text: 'Governing Law' },
  {
    type: 'p',
    text: 'This policy will be governed by and construed in accordance with the Laws of India and is subject to the exclusive jurisdiction of the courts of Telangana.',
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      effectiveDate="April 5, 2026"
      blocks={blocks}
    />
  );
}
