import type { Metadata } from 'next';
import LegalPage, { type LegalBlock } from '@/components/LegalPage';

export const metadata: Metadata = {
  title: 'Disclaimers',
  description:
    'Disclaimers covering general information, marketplace role, advisory and consulting, user-generated content, payments, technical operation, and more.',
};

const blocks: LegalBlock[] = [
  { type: 'h2', text: 'General Information Disclaimer' },
  {
    type: 'p',
    text: 'The information, listings, profiles, and content displayed on this Website are provided by independent Users (Sellers and Purchasers). While we strive to maintain accuracy, the Website does not warrant that any information, description, portfolio, or representation made by a User is accurate, complete, or reliable. All content is provided "as is" without warranties of any kind. The Products and Software provided on the Seller\'s profile have nothing to do with the Company\'s products and the Company provides no representations or warranties, express or implied, with respect to the Products and Services offered by the Seller on the Website.',
  },

  { type: 'h2', text: 'Marketplace Role Disclaimer' },
  {
    type: 'p',
    text: 'The Website is a facilitator or platform created by the Company to connect Users with each other. We do not:',
  },
  {
    type: 'ul',
    items: [
      'Provide freelance services ourselves.',
      'Act as employer, agent, or representative of any User.',
      'Control or direct the quality, timing, legality, or delivery of services.',
      'Guarantee the performance, conduct, or abilities of any Seller or Purchaser.',
    ],
  },
  {
    type: 'p',
    text: 'Users independently enter into service contracts with each other. The Company is not a party to such agreements.',
  },

  { type: 'h2', text: 'Advisory and Consulting' },
  {
    type: 'p',
    text: 'The Website contains content, communication channels and details of Products and Services and the foregoing have been provided for facilitating communication between Users. The content provided therein does not constitute any professional, legal, medical, financial, accounting, business, emotional, psychological or personal advisory by the Company. Users should exercise independent judgement and carry out research where appropriate.',
  },

  { type: 'h2', text: 'User-Generated Content Disclaimer' },
  {
    type: 'p',
    text: 'All reviews, ratings, profiles, posts, portfolios, and uploaded files are generated by Users. The Company or the Website:',
  },
  {
    type: 'ul',
    items: [
      'Does not verify User-generated content except for basic compliance checks.',
      'Is not responsible for any offensive, incorrect, misleading, or harmful content posted by Users.',
      'Reserves the right to remove User-generated content that violates policies but does not assume an obligation to do so.',
    ],
  },

  { type: 'h2', text: 'Payment & Transaction Disclaimer' },
  {
    type: 'p',
    text: 'The Company acts as an escrow platform wherein it accepts payments from the Purchaser and holds them till the successful delivery of Products and Services is confirmed to the Company via the Website. Said payment is released subject to withholding or deduction of Commission, taxes (direct and indirect), fees, currency conversion charges and bank charges. The Company facilitates communication between Users, which is generally followed by monetary transactions. However, the Company does not guarantee:',
  },
  {
    type: 'ul',
    items: [
      'That Sellers will deliver the Product and Service as promised.',
      'That Buyers will approve or accept the delivery.',
      'That refunds will be issued unless explicitly governed by Company policy.',
    ],
  },
  {
    type: 'p',
    text: "All disputes between Users must be resolved directly, except where the platform's dispute resolution rules apply.",
  },

  { type: 'h2', text: 'Technical Disclaimer' },
  {
    type: 'p',
    text: 'The Website does not guarantee:',
  },
  {
    type: 'ul',
    items: [
      'Error-free operation.',
      'That bugs will be corrected immediately.',
      'Compatibility with all devices or browsers.',
    ],
  },
  {
    type: 'p',
    text: 'The Website may be temporarily unavailable due to maintenance, technical issues, or events outside our reasonable control. We bear no liability for any losses arising from such interruptions.',
  },

  { type: 'h2', text: 'Third-Party Links and Content' },
  {
    type: 'p',
    text: 'The Website may contain links to third-party websites, services, or resources. We do not endorse, control, or assume responsibility for any third-party content, products, or services. Your interactions with third parties are governed by their own terms and policies.',
  },
];

export default function DisclaimersPage() {
  return (
    <LegalPage
      title="Disclaimers"
      effectiveDate="April 5, 2026"
      blocks={blocks}
    />
  );
}
