import { memo } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { SEO } from '../components/SEO';
import { Shield } from 'lucide-react';

const PrivacyPolicyPage = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <SEO
        title="Privacy Policy"
        description="Flyrlink Privacy Policy - Learn how we collect, process, use, store and disclose your personal data. Your privacy is important to us."
        keywords="flyrlink privacy policy, data protection, personal data, DPDP Act, privacy, data security"
      />
      <Navbar />

      <main className="flex-1 bg-gray-50">
        {/* Hero Section */}
        <section className="bg-gradient-to-r from-sky-50 to-blue-50 py-16 md:py-20">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto text-center">
              <div className="inline-flex items-center justify-center px-4 py-2 rounded-full bg-white/80 text-sky-600 text-sm font-medium mb-6 shadow-sm">
                <Shield className="w-4 h-4 mr-2" />
                Your Privacy Matters
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4 leading-tight">
                Privacy Policy
              </h1>
              <p className="text-lg text-gray-600 max-w-2xl mx-auto">
                Effective February 15th, 2026
              </p>
            </div>
          </div>
        </section>

        {/* Content Section */}
        <section className="py-12 md:py-16 bg-white">
          <div className="container mx-auto px-4 max-w-4xl">
            <div className="prose prose-gray max-w-none">

              {/* Introduction */}
              <p className="text-gray-700 leading-relaxed mb-6">
                This Privacy Policy describes how the Company collects, processes, uses, stores and discloses Personal Data of Users of its Website, related services. For the purposes of the Digital Personal Data Protection Act, 2023 ("DPDP Act"), the Company acts as a Data Fiduciary in respect of Personal Data processed through the Website. The Company and its affiliates including its holding companies, parents, subsidiaries and allied partners, recognize the importance of protecting the privacy of Users and their personal data. The Company is committed to safeguard the privacy of Users and their personal data in accordance with applicable data protection laws, regulations and industry standards.
              </p>
              <p className="text-gray-700 leading-relaxed mb-6">
                The collection, processing, disclosure and usage of information by the Company is governed by this Policy, which details out the nature of information collected, contents of information collected, details of processing, protecting, storing and archiving of information by the Company and the reasoning explaining the foregoing. The Company is involved in the business of operating technology platforms, applications and web-interfaces for persons/users to access details of our products, services and software. By accessing and/or using the website/application, you are explicitly consenting to the contents of this Policy. You must read the contents of this Policy before accessing the website/applications.
              </p>

              {/* Your Consent */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Your Consent</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                By visiting the Website or setting up/creating a User Account on the Website for availing the Services on the Website at such time, the User signifies its acceptance to the provisions of the Privacy Policy.
              </p>
              <p className="text-gray-700 leading-relaxed mb-6">
                This Privacy Policy (i) is an electronic record under the Information Technology Act, 2000 read with rules and regulations made thereunder and is generated by a computer system; and (ii) will not require any physical, electronic, or digital signature. In case of any non-compliance of the Privacy Policy by the User, we shall have the right to terminate your access to the Services or any part thereof or your usage rights to the Website immediately or remove non-compliant information or both, as the case may be.
              </p>

              {/* Collection of Information */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Collection of Information</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                The Company may collect information which may include Personal Data and Ancillary Data (defined below) from the User upon registration on the Website or when the User avail the Services. You can browse certain sections of the Website without being a registered member, however, to avail certain Services on the Website, the User is required to register with the Website. For avoidance of doubt, the term Personal Data and Personal Information are going to be used synonymously.
              </p>
              <p className="text-gray-700 leading-relaxed mb-6">
                In accordance with the Digital Personal Data Protection Act, 2023 (DPDP Act), "Personal Data" refers to any data about an individual who is identifiable by or in relation to such data. To provide and improve our services, we collect Personal Data as well as Ancillary Data (information related to how you access and use our platforms). The information we collect falls into the following categories:
              </p>

              <h3 className="text-xl font-semibold text-gray-800 mt-8 mb-3">A. Information You Provide to Us</h3>
              <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                <li><strong>Account & Registration Data:</strong> Information provided during User Account creation, including your name, address, country of residence, email address, phone number, unique identifiers, and account preferences (such as favourites and history).</li>
                <li><strong>Communication Data:</strong> Information you share with us through emails, electronic messages, telephonic conversations, or virtual/online meetings.</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-800 mt-8 mb-3">B. Automatically Collected Information (Ancillary Data)</h3>
              <p className="text-gray-700 leading-relaxed mb-4">
                When you interact with our Products, software, solutions, or content, we automatically gather data regarding your usage patterns to ensure seamless Service provision. This includes:
              </p>
              <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                <li><strong>Device & Network Data:</strong> Your IP address, domain name, and other related network identifiers.</li>
                <li><strong>Usage & Interaction Data:</strong> Timestamps, search queries, text prompts, user feedback, overall user behaviour, and interaction patterns with our services.</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-800 mt-8 mb-3">C. Information from Other Sources</h3>
              <p className="text-gray-700 leading-relaxed mb-6">
                Information legitimately obtained from third parties, partners, or other sources as permitted by applicable law.
              </p>

              <p className="text-gray-700 leading-relaxed mb-4">
                Within the ambit of Personal Data, the Company may collect the following information:
              </p>
              <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                <li>Information provided at the time of account registration including name, address, country details, email ID, phone number, unique identifiers, and preference information including favourites and history.</li>
                <li>Information provided to the Company through email and electronic communication.</li>
                <li>Information provided to us telephonically or through virtual or other online mode of communication.</li>
                <li>Information from other sources.</li>
              </ul>

              <p className="text-gray-700 leading-relaxed mb-6">
                By providing Personal Information and Ancillary Information to the Company, you explicitly consent to the collection, usage and disclosure of the foregoing information, as permitted by the applicable laws. By using our products and services, you are authorizing us to gather, parse data and retain basic data which are related to the provision of the services and products.
              </p>

              {/* Voluntary Disclosure */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Voluntary Disclosure & Data Authenticity</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                All information you share with us is deemed to be disclosed willingly and without any coercion. You are solely responsible for the authenticity and accuracy of the information you provide. The Company does not verify this data and assumes no liability for any misrepresentation, fraud, or negligence regarding the information provided to us.
              </p>

              {/* Usage of Collected Information */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Usage of Collected Information</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                The Company may collect your Personal Data and Ancillary Information for the following purposes:
              </p>
              <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                <li>Improve user experience and communicate with you with regards to its Products, Services, software and promotional offers.</li>
                <li>Address complaints, resolve disputes, and diagnose technical issues.</li>
                <li>Maintain a secure environment on the Website and safeguard the integrity of the Website, the Services, and their users.</li>
                <li>Process payments and recover amounts due in connection with the Services.</li>
                <li>Personalise and enhance User experience on the Website, including sending relevant promotional or marketing communications.</li>
                <li>Identify, prevent, and protect against errors, fraud, and any unlawful or prohibited activities.</li>
                <li>Administer, enforce, and notify User of applicable terms and conditions.</li>
                <li>Process and fulfil User requests for Services and respond to feedback, comments, or queries.</li>
                <li>Communicate with the User for service-related or administrative purposes.</li>
                <li>Enable Our business partners or associates to deliver tailored communications or content to You, where permitted.</li>
                <li>Notify User of important announcements, modifications to the Services, or changes to the Website, policies, or terms governing your relationship with the Company and its affiliates.</li>
                <li>Carry out any other purpose disclosed to You at the time of collection, subject to obtaining Your consent where required.</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mb-6">
                Additionally, the Company may use the information collected for observing, improving and administering quality of Services and Products, for sending information and push notifications towards new updates and changes, for conducting market research, troubleshooting, error protection and other additional objectives which may be implemented by the Company to comply with Applicable Laws and to establish an effective channel of communication.
              </p>

              {/* Disclosure of Collected Information */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Disclosure of Collected Information</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                The Company will not publish your information provided by you. We will treat your information as confidential information and will not sell or lease your information to third parties, save and except for:
              </p>
              <ul className="list-disc pl-6 mb-6 space-y-2 text-gray-700">
                <li>Under the mandate of applicable laws, judicial order, instructions received from regulatory, statutory or local bodies.</li>
                <li>Under the event of merger, acquisition, bankruptcy or takeover of the Company.</li>
                <li>Disclosure within group companies and affiliates with the covenant that information so shared will be maintained with strict confidentiality.</li>
                <li>The Company may disclose your information to provide services, enforce or apply applicable terms and conditions or terms of use, to protect its rights, titles, interests or safety of the Company, its assets and its representatives. This includes providing information to one or more lending partners, and exchanging information with other companies/agencies that work for fraud prevention.</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mb-6">
                You provide explicit consent to the Company for sharing your Personal Information with third parties that provide services on its behalf or with whom the Company has partnered to offer a specific product or service. These third parties are required to maintain necessary confidentiality and secrecy arrangements with the Company. We shall not assume responsibility for the transfer of any personal identification information due to data loss or distribution, media storage delineation or corruption, power outages, natural disasters, civil unrest, acts of vandalism, sabotage, terrorism, or any other unforeseen event beyond our control. Additionally, our Privacy Policy does not extend to the utilization of cookies by our partners and affiliates, as we lack access or authority over such cookies.
              </p>

              {/* Amendment or Update */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Amendment or Update to Personal Information</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                In the event that your Personal information is subject to amendment or update at your end, you may connect with us for corrections, deletion of errors or updating information at Email: <a href="mailto:Contact@flyrlink.com" className="text-sky-600 hover:underline">Contact@flyrlink.com</a>. For verification of changes, we request you to provide supportive documentation or information as may be deemed necessary by the Company to verify changes requested.
              </p>

              {/* Security of Information */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Security of Information</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                At the Company, paramount importance is attributed to the security of Personal and Ancillary Information and for ensuring security of your information, suitable physical, electronic and managerial procedures are in place to safeguard and secure the information collected. When gathering data, we securely gather your personal information on a protected server, employing firewalls for added security. While we cannot ensure absolute security, these measures significantly impede hackers from decrypting your details. We uphold physical, electronic, and procedural safeguards throughout the collection, storage, and disclosure of your information. The Company may use third-party vendors, service providers and suppliers to perform various functions on its behalf, such as managing customer information, analysing data, and maintaining its websites and databases (if any). These service providers are not authorized to use Personal Information for any other purpose or to contact you outside of their contracted services. If you believe your account or information is compromised, please notify the Company immediately via email: <a href="mailto:Contact@flyrlink.com" className="text-sky-600 hover:underline">Contact@flyrlink.com</a>.
              </p>
              <p className="text-gray-700 leading-relaxed mb-6">
                The information and data collected from you may be transferred to, stored, and processed in any location permitted by applicable law. By submitting information to us, you consent to this transfer, storage, and/or processing. We will take reasonable steps to ensure that your information is treated securely and in accordance with this Policy. When accessing the website and its contents, you acknowledge the inherent security risks of transmitting data over the internet. Therefore, your use of the website and application is at your own risk, and we bear no responsibility for any information disclosure resulting from transmission errors, unauthorized access by third parties, or other acts beyond our control. You agree not to hold us liable for any security breaches. Should we become aware of any security breach involving your information, we will promptly notify you and take appropriate action to the best of our ability to address the breach.
              </p>

              {/* Connecting Email Account */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Connecting your User Account to Email Account</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                The User may choose to integrate one or more of your email accounts with your User Account on the Website for enhanced functionality. Such integration will occur only upon your explicit consent, including authentication via a confirmation email sent to your registered email address. The User will be specifically prompted each time to confirm whether you wish to link your email account(s) with your User Account on the Website. Integration will not take place unless you provide express authorization.
              </p>
              <p className="text-gray-700 leading-relaxed mb-6">
                You are advised to carefully review the permissions requested prior to granting consent for integration. You retain full control over such integration and may, at any time, revoke access or de-link your connected email account(s) through the account settings available on the Website. Upon such de-linking, the Company will cease further access to the integrated email account(s), subject to retention requirements under Applicable Law.
              </p>
              <p className="text-gray-700 leading-relaxed mb-6">
                Additionally, where required for account functionality, profile display, or service features, the Company may upload and display your profile image on the Website. By voluntarily providing such image, you consent to its use for the intended Website functionality. You may modify or remove your profile image at any time through your account settings.
              </p>

              {/* Phishing and Online Fraud */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Phishing and Online Fraud</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                There are existing in the market, third party websites, which imitate legitimate website to obtain and steal personal and financial information. Such illegitimate practices are of great concern to the Company and in the event, you come across any such material or interaction from a third party, please report it to email: <a href="mailto:Contact@flyrlink.com" className="text-sky-600 hover:underline">Contact@flyrlink.com</a>. The Company is committed to take all measures necessary to secure the Website and other services and in rare cases, certain users may request you to communicate outside the Website including depositing some money. You should refrain from interacting with such users and should never deposit or send money outside the Website.
              </p>

              {/* Account Deletion */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Account Deletion</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                The User may choose to delete the User Account on the Website and any information associated with it, hereunder at any point of time. Such a request for deletion must be sent in writing to <a href="mailto:Contact@flyrlink.com" className="text-sky-600 hover:underline">Contact@flyrlink.com</a>. In the event that the User makes a request for deletion of User Account or data therein, the User will no longer be able to access the Website and/or use the Services, and we reserve the right to not provide the User any Services through the Website. In the event of your request, we may delete User's information or de-identify it so that it is anonymous and no longer attributable to You. Notwithstanding anything contained herein, we may retain some or all of User's information in accordance with our policies and/or requirements under Applicable Law.
              </p>

              {/* Public Profile */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Public Profile</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                The profile created by the User on the Website is and will be publicly accessible unless otherwise indicated. Public profiles are indexed by search engines such as Google which may include displaying of your profile and information therein as part of the search results. To prevent Google Indexing, you may opt not to have your profile included in the Google indexing.
              </p>

              {/* Exclusions */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Exclusions to the Policy</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                This Policy does not apply to information other than Personal and Ancillary Information collected by us during your access of our Website, products, services and software. This Policy does not apply in case of any information shared by you which is not solicited by the Company. Our Website, products and software may contain links to third party websites and such websites are not under our control. In case you are directed to any of said websites, you are suggested to exercise discretion, and your access and usage of the third-party websites shall be entirely at your own risk, and we disclaim any liability for any issues arising out of your redirection, access and usage of third-party websites and contents thereof.
              </p>

              {/* Retention */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Retention of Information</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                The Company will retain Personal and Ancillary Information as long as it is necessary to fulfil the purposes outlined in this policy, and as permitted by applicable laws. Once the business need is fulfilled or the purpose is no longer valid, the Company will either delete or anonymize the Personal Information. In cases where it is not possible, the Company will isolate the information from any further processing.
              </p>

              {/* Update to Policy */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Update to the Policy</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                This Privacy Policy and contents therein may change from time to time and all updates regarding the same shall be posted on our website. The Company reserves the right to change this Privacy Policy and related documentation as and when it deems fit.
              </p>

              {/* Addressing Concerns */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Addressing Your Concerns</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                In the event of a security breach of Company systems, the Company will notify you through your authorized email address within 72 hours of the discovery of the breach. You may request details of personal information which we hold about you from the undersigned. There is no fee payable for this. If you would like a copy of the information held on you, please write to us at Email: <a href="mailto:Contact@flyrlink.com" className="text-sky-600 hover:underline">Contact@flyrlink.com</a>.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                In accordance with the Information Technology Act, 2000 and the rules made thereunder, the name and contact details of the Grievance Officer are provided below:
              </p>
              <div className="bg-gray-50 rounded-xl p-6 mb-6 border border-gray-100">
                <p className="text-gray-700 mb-1"><strong>Name:</strong> Raj Bharath Bandi</p>
                <p className="text-gray-700 mb-1"><strong>Email:</strong> <a href="mailto:Raj.Bharath@flyrlink.com" className="text-sky-600 hover:underline">Raj.Bharath@flyrlink.com</a></p>
                <p className="text-gray-700"><strong>Address:</strong> Unit 407, 4th floor Jain Sadguru Image capital park, Image garden road, Hyderabad – 500081.</p>
              </div>

              {/* Governing Law */}
              <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Governing Law</h2>
              <p className="text-gray-700 leading-relaxed mb-6">
                This policy will be governed by and construed in accordance with the laws of India and subjected to the exclusive jurisdiction of Courts of Telangana.
              </p>

            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default memo(PrivacyPolicyPage);
